artist:
  name: Cosmic Cowboy Media
  tagline: Greg Shaddix - podcaster, songwriter & maker of balloon animals out of the truth
  seo_title: Podcaster, Singer, Songwriter
  # seo_description:
  contact_twitter_username: gshaddixmusic
  # contact_phone: 
  contact_email: cosmiccowboymedia@gmail.com

social:
  - name: Facebook
    url: https://www.facebook.com/TheMockingbirdPodcast/
  - name: Instagram
    url: https://www.instagram.com/mockingbirdmedia/
  - name: Twitter
    url: https://twitter.com/gshaddixmusic
  - name: Youtube
    url: https://www.youtube.com/channel/UC-6_oRtq4a_EGpr2DYw_RGA/
  - name: Spotify
    url: https://open.spotify.com/album/0o8UuUJlwQw6psy4fyUOnl

site_language: en
